### ISSUE TITLE
Improve the fonts and favicon.ico

### ISSUE THREAD

**Issue by kayceenuel** [rohitagr0310/Bookflow-app#244] opened 2023-10-03 19:58 UTC
### **Can** I work on this?

**Comment by rohitagr0310** [comment] 2023-10-04 04:47
Go Ahead! I have assigned the issue to you @kayceeNuel .

Work on a new branch with the feature as the branch name.

When you create a pull request, request review from @rohitagr0310 , @jain-anshika or , @qaidjoharj53

**Comment by aparna03dubey** [comment] 2023-10-04 11:41
@rohitagr0310 @jain-anshika  @qaidjoharj53  It would be great if you assign me this issue for hacktober fest.

**Comment by rohitagr0310** [comment] 2023-10-04 12:13
@aparna03dubey I am sorry, but the issue has already been assigned, if the issue is not complete and becomes inactive, only then will we reassign it

Thank you

**Comment by kayceenuel** [comment] 2023-10-04 13:32
> Go Ahead! I have assigned the issue to you @kayceeNuel .
> 
> Work on a new branch with the feature as the branch name.
> 
> When you create a pull request, request review from @rohitagr0310 , @jain-anshika or , @qaidjoharj53

Alright then.

**Comment by jain-anshika** [comment] 2023-10-04 19:42
#254 
@kayceeNuel 
who ever creates a PR first will be merged and other will be closed as not planned.

**Closed as completed** 2023-10-11 16:23 UTC
Labels: enhancement, Hacktoberfest-accepted
