### ISSUE TITLE
Single column layout for mobile screens 

### ISSUE THREAD

**Issue by ashishk1331** [rohitagr0310/Bookflow-app#220] opened 2023-10-02 17:19 UTC
![Screenshot_20231002-224602_Chrome.jpg](https://github.com/rohitagr0310/Bookflow-app/assets/44055846/9ba39282-017b-45f1-9820-eb660dd95922)

The two column layout should shift to one column layout on mobile screens. 

Solution:
Implement grid layout for it that will switch  to single column on mobile screen.

**Comment by rohitagr0310** [comment] 2023-10-03 04:28
@ashishk1331 Will the single layout work with react application as well as laptop size screens

**Comment by ashishk1331** [comment] 2023-10-03 05:12
Yes, media queries can handle different screen sizes and shift columns number accordingly.

**Comment by rohitagr0310** [comment] 2023-10-03 05:20
Then it would be a great feature for user experience.

**Comment by rohitagr0310** [comment] 2023-10-03 09:17
i have assigned the issue to you.

work on a new branch with the feature as the branch name

when you create a pull request, request review from @jain-anshika or @jayesh2474

**Comment by ashishk1331** [comment] 2023-10-03 09:58
@rohitagr0310 Okay. Acknowledged.

**Comment by AdityaRaj23** [comment] 2023-10-03 15:20
I have worked on this issue as a part of hacktoberfest and my work is complete can I push my work for review?
![IMAGE 2023-10-03 20:49:38](https://github.com/rohitagr0310/Bookflow-app/assets/95625520/a726a08c-6969-4c7f-b515-16cf975a9a30)

**Comment by AdityaRaj23** [comment] 2023-10-03 15:26
I have worked on this issue as a part of hacktoberfest and my job is done can I push my work for review?
![alpha](https://github.com/rohitagr0310/Bookflow-app/assets/95625520/0fdf4c9e-e9d2-470b-a402-b9946be9b05b)

**Comment by rohitagr0310** [comment] 2023-10-03 16:42
@AdityaRaj23 I respect your enthusiasm, but the issue has already been assigned to @ashishk1331 . if he is ok to share the work and issue with you, I will assign it to both of you

**Comment by ashishk1331** [comment] 2023-10-03 16:58
Woah! This is outrageous. However, the event is meant to be welcoming and if you've already solved the issue, including the white space thing, and moderators are happy with it, go ahead and make a PR.

However, a **note**
Understand how the things work here. If one person is assigned to the issue, you should not make such moves. Unless the person assigned has not shown any sign or had not reported in days, then only ask to work on the issue.

Well, in other words it's kind of a race and the person who gets in first gets served. 
Mods you decide. @rohitagr0310

**Comment by rohitagr0310** [comment] 2023-10-03 17:04
@ashishk1331 I belive that you should work on this issue as you open it

**Comment by ashishk1331** [comment] 2023-10-03 17:06
As you say. I'll do it then.

**Comment by AdityaRaj23** [comment] 2023-10-03 17:15
Certainly, I'm comfortable with this. It marks my inaugural open-source contribution to any project. I stumbled upon this project through Discord, and although I attempted to access the code of conduct, I couldn't open it. This left me somewhat apprehensive about making a request to join the project. I didn't want to deter a more experienced contributor from improving it, as I lack confidence at this stage. Nonetheless, I've gained valuable experience while coding for this project, and I will bear this lesson in mind for future endeavours.

**Comment by rohitagr0310** [comment] 2023-10-03 17:21
That's fantastic to hear that you're comfortable with your inaugural open-source contribution! Don't worry too much about your level of experience; every contributor, regardless of their experience level, plays an important role in open-source projects. Your willingness to learn and grow is what matters most.

As for the issue with the code of conduct, thank you for bringing it to our attention. We'll make sure to address that issue promptly. If you ever have questions or need assistance with anything related to the project, feel free to reach out. We're here to help and support each other on this journey. Keep up the great work, and remember that every contribution, big or small, is a step toward becoming a more experienced and confident open-source contributor. We look forward to seeing your future endeavors in the open-source community!

**Comment by ashishk1331** [comment] 2023-10-03 17:46
> Certainly, I'm comfortable with this. It marks my inaugural open-source contribution to any project. I stumbled upon this project through Discord, and although I attempted to access the code of conduct, I couldn't open it. This left me somewhat apprehensive about making a request to join the project. I didn't want to deter a more experienced contributor from improving it, as I lack confidence at this stage. Nonetheless, I've gained valuable experience while coding for this project, and I will bear this lesson in mind for future endeavours.

I didn't mean to sound discouraging or rude. I'm not any highly esteemed monk with all knowledge and stuff. I am myself a noob who keeps on learning and exploring things. Don't lose confidence over such petty issues. Have a competitive mindset and move on! If you need any help regarding anything feel free to contact me. Even if you want me to tell you about other repos to contribute to.

**Comment by AdityaRaj23** [comment] 2023-10-03 18:17
> > Certainly, I'm comfortable with this. It marks my inaugural open-source contribution to any project. I stumbled upon this project through Discord, and although I attempted to access the code of conduct, I couldn't open it. This left me somewhat apprehensive about making a request to join the project. I didn't want to deter a more experienced contributor from improving it, as I lack confidence at this stage. Nonetheless, I've gained valuable experience while coding for this project, and I will bear this lesson in mind for future endeavours.
> 
> I didn't mean to sound discouraging or rude. I'm not any highly esteemed monk with all knowledge and stuff. I am myself a noob who keeps on learning and exploring things. Don't lose confidence over such petty issues. Have a competitive mindset and move on! If you need any help regarding anything feel free to contact me. Even if you want me to tell you about other repos to contribute to.

No you didn't and you are right on that race thing, open source is for contribution not competition, will surely contact you if I need any help or assistance in future ...

**Comment by rohitagr0310** [comment] 2023-10-04 04:53
The issue is complete 

Thank you for your contribution

**Closed as completed** 2023-10-04 04:53 UTC
Labels: enhancement, Hacktoberfest-accepted
