### ISSUE TITLE
Improving the 'Contact Us' Section with New Functionalities and Enhanced User Interface.

### ISSUE THREAD

**Issue by vinayakjaas** [rohitagr0310/Bookflow-app#239] opened 2023-10-03 18:14 UTC
I'm eager to contribute to the "Contact Us" section by introducing new functionalities and enhancing the user interface. Please assign this task to me.
![image](https://github.com/rohitagr0310/Bookflow-app/assets/96948435/9518a8a5-22f1-4b43-8357-ea59ed1a711c)

**Comment by jain-anshika** [comment] 2023-10-03 19:13
Go Ahead! I have assigned the issue to you @vinayakjaas  .

Work on a new branch with the feature as the branch name.
Also add the screenshots after making changes.

When you create a pull request, request review from @rohitagr0310  , @jain-anshika  or , @qaidjoharj53

**Comment by qaidjoharj53** [comment] 2023-10-03 19:41
@vinayakjaas You must not change the content (like name, email, phone no.) on the contact-us page and also you must not breach the privacy.

If found so, you'll be reported and will be discarded.

Just follow the Code of Conduct.

**Comment by vinayakjaas** [comment] 2023-10-03 19:44
@qaidjoharj53 I work only interface and style part

**Comment by qaidjoharj53** [comment] 2023-10-03 21:09
@vinayakjaas Ohk then, No problem.

All the best!

**Comment by vinayakjaas** [comment] 2023-10-04 18:01
@rohitagr0310 @jain-anshika  Please Review my PR

**Comment by rohitagr0310** [comment] 2023-10-04 18:42
The issue is complete and the pr has been merged

Thank you for your contribution

**Closed as completed by rohitagr0310** 2023-10-04 18:42 UTC
Labels: documentation, Hacktoberfest-accepted
