### ISSUE TITLE
Bug: build file not configured in .gitignore file

### ISSUE THREAD

**Issue by Gobinath-B** [rohitagr0310/Bookflow-app#248] opened 2023-10-04 06:46 UTC
### There is a problem when we run `npm run build` the build files are tracked by git.
. To ignore this scenario we should add build to .gitignore file

**Comment by rohitagr0310** [comment] 2023-10-04 08:14
Go Ahead! I have assigned the issue to you @Gobinath-B  .

Work on a new branch with the feature as the branch name.

When you create a pull request, request review from @rohitagr0310 , @jain-anshika or , @qaidjoharj53

**Comment by rohitagr0310** [comment] 2023-10-04 12:36
The issue is complete and the pr has been merged

Thank you for your contribution

**Closed as completed by rohitagr0310** 2023-10-04 12:36 UTC
Labels: bug, Hacktoberfest-accepted
